version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sqljg#12
      MYSQL_DATABASE: newsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    DATABASE_URL: mysql+mysqlconnector://root:Sqljg#12@localhost/newsdb

volumes:
  mysql_data:

